GET /api/news HTTP/1.1
Host: localhost:5000

###

GET /api/users HTTP/1.1
Host: localhost:5000

### Get desks
GET /api/desks HTTP/1.1
Host: localhost:5000

### Get Favourites
GET /api/desks/favourites HTTP/1.1
Host: localhost:5000

### Get bookings
GET /api/bookings HTTP/1.1
Host: localhost:5000

### Get bookings by user
GET /api/bookings/bookingsbyuser?user_id=1 HTTP/1.1
Host: localhost:5000

### Get last booked
GET /api/bookings/lastbooked?user_id=1 HTTP/1.1
Host: localhost:5000

### Find desk by booking
GET /api/bookings/finddesk?user_id=3&date=3123-12-23 HTTP/1.1
Host: localhost:5000

### Add booking
POST /api/bookings/bookdesk HTTP/1.1
Host: localhost:5000
Content-Type: application/json

{
    "user_id": "1",
    "desk_id": "101",
    "date": "2024-05-13-2024-05-20"
}

### Remove booking
DELETE /api/bookings/removebooking HTTP/1.1
Host: localhost:5000
Content-Type: application/json

{
    "user_id": "1",
    "desk_id": "101",
    "date": "2025-10-20-2025-10-25"
}

### Get Booking for certain user and date
GET /api/bookings/getbookinguserdate?user_id=1&date=2025-10-18 HTTP/1.1
Host: localhost:5000

### Favourite desks
POST /api/desks/favouritedesk?desk_id=DUB05-2-L-19&user_id=1 HTTP/1.1
Host: localhost:5000

### Unfavourite desks
DELETE /api/desks/removefavourite?desk_id=DUB05-2-L-19&user_id=1 HTTP/1.1
Host: localhost:5000

### Get favourite desk for certain user
GET /api/desks/favouritesbyuser?user_id=1 HTTP/1.1
Host: localhost:5000


### Filter desks by floor
GET /api/desks/filterbyfloor?floor=1 HTTP/1.1
Host: localhost:5000

### What users have booked desks at a certain date
GET /api/bookings/bookingsbydate?date=3123-12-23 HTTP/1.1
Host: localhost:5000
Content-Type: application/json

### Get all carpooler
GET /api/carpools/carpooler HTTP/1.1
Host: localhost:5000

### Get all Carpoolee
GET /api/carpools/carpoolee HTTP/1.1
Host: localhost:5000

### Add carpooler
POST /api/carpools/addcarpooler HTTP/1.1
Host: localhost:5000
Content-Type: application/json

{
    "user_id": "2",
    "eircode": "D07 H6K8"
}

### Add carpoolee
POST /api/carpools/addcarpoolee HTTP/1.1
Host: localhost:5000
Content-Type: application/json

{
    "user_id": "3",
    "eircode": "D24 Y99R"
}

### Remove carpooler
DELETE /api/carpools/removecarpooler HTTP/1.1
Host: localhost:5000
Content-Type: application/json

{
    "user_id": "1"
}

### Remove carpoolee
DELETE /api/carpools/removecarpoolee HTTP/1.1
Host: localhost:5000
Content-Type: application/json

{
    "user_id": "3"
}

### Get distance between two eircodes
GET /api/carpools/distance?eircode1=D24 FKT9&eircode2=D24 Y99R HTTP/1.1
Host: localhost:5000

### Get list of carpooler closest to you
GET /api/carpools/closestcarpooler?user_id=3 HTTP/1.1
Host: localhost:5000

### Get tasks
GET /api/tasks HTTP/1.1
Host: localhost:5000

### Get tasks by user
GET /api/tasks/usertasks?user_id=1 HTTP/1.1
Host: localhost:5000

### Add task
POST /api/tasks/addtask HTTP/1.1
Host: localhost:5000
Content-Type: application/json

{
    "user_id": "1",
    "task_name": "Clean the kitchen",
    "task_description": "Clean the kitchen and put away the dishes",
    "task_date": "2022-09-15",
    "task_time": "12:00:00",
    "task_colour": "red"
}

### Remove task
DELETE /api/tasks/removetask HTTP/1.1
Host: localhost:5000
Content-Type: application/json

{
    "id": "2"
}

### Get building
GET /api/buildings HTTP/1.1
Host: localhost:5000

### Get floor from building
GET /api/buildings/floors?building=Building A HTTP/1.1
Host: localhost:5000

### test
GET /api/bookings/test HTTP/1.1
Host: localhost:5000

### test 2
DELETE /api/bookings/test2 HTTP/1.1
Host: localhost:5000
Content-Type: application/json

{
    "user_id": "1",
    "desk_id": "101",
    "date": "2025-10-20-2025-10-25"
}